import Head from 'next/head'
import Image from 'next/image'
import { Todo } from '../components/Todo'
import styles from '../styles/Home.module.css'
import fs from "fs/promises"
import { useEffect, useState } from 'react'
import Link from 'next/link'

type HomeProps = {
  name: string,
  todos: Todo[]
}

export default function Home(props: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by @deadparrot@mastodon.social" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello {props.name}!
        </h1>
        <Todo items={props.todos} />
        <Link href="/about">Go to About</Link>
      </main>
      
    </div>
  )
}

export async function getServerSideProps() {
  const props = await fetch("https://swapi.dev/api/people/42").then(res => res.json())
  const todos: Todo[] = await fs.readFile("./data.json").then(buffer => JSON.parse(buffer.toString()))
  return {
    props: {
      ...props,
      todos
    }
  }
}